"""add_session_visibility_invite

Revision ID: c8bff91372a7
Revises: d0e4deeb3778
Create Date: 2026-08-07 02:19:09.255730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bff91372a7'
down_revision: Union[str, Sequence[str], None] = 'd0e4deeb3778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('visibility', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('invite_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_sessions_invite_code'), 'sessions', ['invite_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_invite_code'), table_name='sessions')
    op.drop_column('sessions', 'invite_code')
    op.drop_column('sessions', 'visibility')
    # ### end Alembic commands ###
