"""add ruleset tables and columns

Revision ID: e1e343a8cbb6
Revises: c8bff91372a7
Create Date: 2026-08-07 12:41:44.794966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e343a8cbb6'
down_revision: Union[str, Sequence[str], None] = 'c8bff91372a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('base_ruleset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('overrides_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rulesets_account_id'), 'rulesets', ['account_id'], unique=False)
    op.add_column('characters', sa.Column('ruleset_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('ruleset_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ruleset_id')
    op.drop_column('characters', 'ruleset_id')
    op.drop_index(op.f('ix_rulesets_account_id'), table_name='rulesets')
    op.drop_table('rulesets')
    # ### end Alembic commands ###
