"""add_instance_columns

Revision ID: e227f9204261
Revises: 07604117056f
Create Date: 2026-08-07 13:28:36.146302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e227f9204261'
down_revision: Union[str, Sequence[str], None] = '07604117056f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('adventure_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('dm_account_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('ai_dm_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('sessions', sa.Column('state_version', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('sessions', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('saved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sessions_adventure_id'), 'sessions', ['adventure_id'], unique=False)
    op.create_index(op.f('ix_sessions_dm_account_id'), 'sessions', ['dm_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_dm_account_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_adventure_id'), table_name='sessions')
    op.drop_column('sessions', 'saved_at')
    op.drop_column('sessions', 'last_active_at')
    op.drop_column('sessions', 'state_version')
    op.drop_column('sessions', 'ai_dm_enabled')
    op.drop_column('sessions', 'dm_account_id')
    op.drop_column('sessions', 'adventure_id')
    # ### end Alembic commands ###
