"""add_campaigns_and_campaign_members

Revision ID: ec604bad1607
Revises: 11c00ee745d7
Create Date: 2026-08-06 01:19:29.828092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec604bad1607'
down_revision: Union[str, Sequence[str], None] = '11c00ee745d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_members',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'account_id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ruleset_id', sa.String(), nullable=True),
    sa.Column('module_ids', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('dm_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.add_column('sessions', sa.Column('campaign_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sessions_campaign_id'), 'sessions', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_campaign_id'), table_name='sessions')
    op.drop_column('sessions', 'campaign_id')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('campaign_members')
    # ### end Alembic commands ###
